#!/bin/bash
awsaccountnumber () {
        aws ec2 describe-security-groups --group-names 'Default' --query 'SecurityGroups[0].OwnerId' --output text $*
}

if [ "x$1" = "x" ]; then
  echo usage: $0 username password authemail authkey zoneid 
  exit 1
fi

#acct=$(awsaccountnumber)
bucket=${6:-emil}
authorizerDirectory=../basic-auth-api-gateway

zip -j updater.zip *.js && aws s3 cp updater.zip s3://$bucket
rm updater.zip

zip -j authorizer.zip $authorizerDirectory/*.js && aws s3 cp authorizer.zip s3://$bucket
rm authorizer.zip


if [ $? -ne 0 ]; then
  echo error creating function. If it already exists, use
  echo aws lambda delete-function --function-name $fn_name
fi

aws cloudformation create-stack \
  --stack-name ipupdater \
  --template-body file://update-ip-cfn.yaml \
  --capabilities CAPABILITY_IAM \
  --parameters \
    ParameterKey=BasicAuthUsername,ParameterValue=$1 \
    ParameterKey=BasicAuthPassword,ParameterValue=$2 \
    ParameterKey=CloudFlareAuthorizationEmail,ParameterValue=$3 \
    ParameterKey=CloudFlareAuthorizationKey,ParameterValue=$4 \
    ParameterKey=CloudFlareZoneId,ParameterValue=$5 \
    ParameterKey=Bucket,ParameterValue=$bucket
